// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oilmymlywffkkdipvbbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pbG15bWx5d2Zma2tkaXB2YmJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODM5MzcsImV4cCI6MjA2Mzg1OTkzN30.q59rsCMi0W5uqNLtHIyyNPm-VNk_reGNUnZV4v6wAZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);